name: ServerCore
version: '${project.version}'
main: de.leghast.servercore.ServerCore
api-version: '1.20'
authors: [GhastCraftHD]
description: The core server plugin for the LeGhast.de network
website: https://www.leghast.de
commands:
  vanish:
